env = QT_QPA_PLATFORMTHEME,qt6ct

#change the default editor keybind to neovim in alacritty
$editor = alacritty -e nvim

#change the default terminal to alacritty
$terminal = alacritty
env = TERMINAL,alacritty

#change the default file manager to thunar
$fileManager = thunar
env = FILEMANAGER,thunar

#change workspace numbers for the monitors
workspace = 2, monitor:desc:ASUSTek COMPUTER INC PG27AQDM R6LMRS030585, default:true
workspace = 1, monitor:desc:Acer Technologies VG271U 0x01915550, default:true
workspace = 3, monitor:desc:Microstep MAG274QRF-QD CA8A281500266, default:true

bind = SUPER, M, exec, /usr/local/bin/mic-toggle
bind = SUPER SHIFT, M, exec, /usr/local/bin/audio-mode-switcher

exec-once = /usr/local/bin/audio-mode-switcher desk
