context.modules = [
    # Virtual Speaker: apps play here → forwards to Scarlett headphone out
    { name = libpipewire-module-loopback
      args = {
          node.description = "Virtual Speaker"
          capture.props = {
              node.name      = "Virtual_Speaker"
              media.class    = "Audio/Sink"
              audio.position = [ FL FR ]
              audio.rate     = 48000
          }
          playback.props = {
              node.name                       = "Virtual_Speaker_Exhaust"
              target.object                   = "audio-switch-managed-output"
              audio.rate                      = 48000
              node.passive                    = true
              audio.position                  = [ AUX0 AUX1 ]
              session.suspend-timeout-seconds = 0
              node.dont-reconnect             = true
              node.dont-fallback              = true
              node.linger                     = true
          }
      }
    }

    # Virtual Mic: apps record from here ← forwards from Scarlett input 1
    { name = libpipewire-module-loopback
      args = {
          node.description = "Virtual Mic"
          capture.props = {
              node.name           = "Virtual_Mic_Intake"
              target.object       = "audio-switch-managed-input"
              audio.rate          = 48000
              node.passive        = true
              audio.position      = [ AUX0 ]
              node.dont-reconnect = true
              node.dont-fallback  = true
              node.linger         = true
          }
          playback.props = {
              node.name               = "Virtual_Mic"
              media.class             = "Audio/Source"
              audio.position          = [ FL FR ]
              audio.rate              = 48000
              channelmix.upmix        = true
              channelmix.upmix-method = simple
          }
      }
    }
]
